# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solution.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("solution.proto", :syntax => :proto3) do
    add_message "SolutionRequest" do
      optional :input, :string, 1
    end
    add_message "SolutionReply" do
      optional :part1_solution, :int64, 1
      optional :part2_solution, :int64, 2
    end
  end
end

SolutionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SolutionRequest").msgclass
SolutionReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SolutionReply").msgclass
