# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: solution.proto for package ''

require 'grpc'
require 'solution_pb'

module Solution
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Solution'

    rpc :GetSolution, ::SolutionRequest, ::SolutionReply
  end

  Stub = Service.rpc_stub_class
end
